-- 011_tutor_publish_guard.sql
-- Publish-guard + mock flag for the AI tutor (deferred nits from the tutor review).
--
-- 1) ai_response_drafts.message_id ties a draft to the exact assistant message it
--    was published from, replacing the response-text-equality guard in
--    publishAnswer. The partial unique index makes the double-publish check
--    race-safe: a second publish of the same message hits the index instead of
--    inserting a duplicate draft.
-- 2) ai_messages.is_mock records at insert time that a reply came from the local
--    stub, so mock-era messages keep their "Stub model" label after the real
--    model goes live (the transient ?mock=1 flag disappears on reload).

alter table public.ai_response_drafts
  add column if not exists message_id uuid references public.ai_messages(id) on delete set null;

create unique index if not exists ai_drafts_one_per_message
  on public.ai_response_drafts(message_id) where message_id is not null;

alter table public.ai_messages
  add column if not exists is_mock boolean not null default false;

-- Backfill message_id for pre-existing drafts, but only where the response text
-- matches exactly one assistant message in the draft's conversation — an
-- ambiguous match would guess, and a wrong guess blocks publishing the message
-- that actually lacks a draft.
update public.ai_response_drafts d
set message_id = m.id
from public.ai_messages m
where d.message_id is null
  and d.conversation_id is not null
  and m.conversation_id = d.conversation_id
  and m.role = 'assistant'
  and m.content = d.response
  and (
    select count(*)
    from public.ai_messages m2
    where m2.conversation_id = d.conversation_id
      and m2.role = 'assistant'
      and m2.content = d.response
  ) = 1;

-- All messages so far were generated by the stub (MODEL_SERVER_URL has never
-- been set in any deployed environment).
update public.ai_messages
set is_mock = true
where role = 'assistant';
